apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tyk-sre-tool.fullname" . }}
  labels:
    {{- include "tyk-sre-tool.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tyk-sre-tool.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tyk-sre-tool.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tyk-sre-tool.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
